### ISSUE TITLE
Other chipsets

### ISSUE THREAD

**Issue by grodansparadis** [mwaylabs/fruitymesh#100]
Theoretically, would fruitymesh port well to other manufactures chip sets, ST BRNG1/2, esp32, Microchip RN4870,71 etc

**Comment by mariusheil** [comment]
Theoretically, yes. Some work has been done to put nordic specific code into a HAL, but that work is not yet finished and it is probably quite some work to get it done.

**Comment by mariusheil** [comment]
We do now support the nRF52840 as well and have a restructuring of the HAL on our roadmap. This will allow anybody to port it to a different platform.
