### ISSUE TITLE
Is fruitymesh still being developed?

### ISSUE THREAD

**Issue by romankc** [mwaylabs/fruitymesh#102]
I see that about a year ago you were looking to hire somebody to work on fruitymesh and that there have been no updates for over a year. Is this project still actively being developed?

**Comment by volkrass** [comment]
Dear @romankc, yes it is still under heavy development. 
A brand new version with a lot of improvements will be available in few days. Stay tuned!

**Comment by romankc** [comment]
We recently started building a product with the regular Nordic Mesh SDK so I am excited to try your implementation instead. Certainly willing to pay reasonable licensing fees for advanced features.

**Comment by volkrass** [comment]
@romankc you can reach me out at https://bluerange.io/contact/

**Comment by volkrass** [comment]
New version is out.
