### ISSUE TITLE
Add Roadmap & Changelog to our README 

### ISSUE THREAD

**Issue by volkrass** [mwaylabs/fruitymesh#115]
To keep the community up-to-date, we should improve our README to give an overview what we are working on and what have been fixed with latest version (changelog).

**Comment by deviousasti** [comment]
Is the NRF51 supported?
In `featuresets`, there's no nrf51, only nrf52 - it seems to have been removed in recent commits.

**Comment by MichalBiolik** [comment]
Hi @deviousasti . NRF51 is depricated - it is still supported, but no new features will be added for NRF51 and it may come out of support soon. Regarding featureset - you can always create your own featureset targeted for NRF51 device.

**Comment by deviousasti** [comment]
Thank you for the response.

**Comment by mariusheil** [comment]
Closing this as it was inactive for some time, feel free to reopen.
