### ISSUE TITLE
How to send messages via UART?

### ISSUE THREAD

**Issue by NilsMinor** [mwaylabs/fruitymesh#122]
Hi,

first of all I want to thank you for your awesome project!

I have a valid image running on a nrf51 evaluation board. When I reset the module I get valid informations via UART. But when I try to get information via command I do not get an answer from the module or I get 'Command not found'.
I tried the commands 
- get_info this
- get_modules this

Do I need to send an additional terminating character like \n? What am I doing wrong? ^^
Thanks,
Nils

**Comment by NilsMinor** [comment]
Hi,
ok you can close my question, I found my mistake.
My serial tool added an CR+LF after the command. The correct option was to add only a CR.
Thanks anyway :D

**Comment by mariusheil** [comment]
perfect :-)
