### ISSUE TITLE
Bluetooth 5 Long Range

### ISSUE THREAD

**Issue by marcantoinebouchard** [mwaylabs/fruitymesh#156]
Hi,

The problem I have trying to make it work with Long Range is there is no "Connectable and scannable undirected" advertising type in Bluetooth 5 Long Range spec. Does the FruityMesh design lie on this advertising type?

Thanks,
Marc

**Comment by mariusheil** [comment]
Hi,

no, the design of FruityMesh does not rely on this type of advertising. You need to have the possibility to distribute an advertising packet that informs surrounding node about the clusterSize and some other information. Also, you need to be connectable (of course). If these conditions are met, you can probably implement long range support.

It is on our roadmap as well, but we have a lot of other requested features that we are working on and it hasn't yet gotten a high enough priority internally.

Marius

**Comment by mariusheil** [comment]
Closing this for now. If we have more to share such as a roadmap, we will announce it.
