### ISSUE TITLE
Slack channel, or something equivalent?

### ISSUE THREAD

**Issue by Rewbert** [mwaylabs/fruitymesh#157]
Hi!

I was wondering if there's a Slack channel or something similar where I could post some questions?

Thanks in advance,
Robert

**Comment by mariusheil** [comment]
Hello,

you can simply open an issue here and label it as "question". This way it will be persisted for other people to read if they have a similar question. If there is something more private that you do not want to post to github, you could write us an E-Mail instead.

Marius

**Comment by Rewbert** [comment]
Thanks for the quick reply!
