### ISSUE TITLE
Where are module IDs defined?

### ISSUE THREAD

**Issue by Rewbert** [mwaylabs/fruitymesh#158]
Hi!

Where are module ID's for the different modules defined? E.g 1 for Beaconing module. I can see that a module id is passed in as an argument to the constructor but I can't trace it and find a call site.

Trying to wrap my head around how modules work so that I can write an example module of my own.

Thanks

**Comment by Rewbert** [comment]
Nevermind, I found it the second after I wrote this issue. It is in PrimitiveTypes.h.

**Comment by mariusheil** [comment]
Hi,

make sure to read the documentation on module ids:
https://www.bluerange.io/docs/fruitymesh/Specification.html#ModuleIds

Also, you can follow this tutorial:
https://www.bluerange.io/docs/fruitymesh/Implementing-a-Custom-Module.html
