### ISSUE TITLE
Can't implement custom module

### ISSUE THREAD

**Issue by microcosm** [mwaylabs/fruitymesh#16]
Hi,

I am following the instructions here:
https://github.com/mwaylabs/fruitymesh/wiki/Implementing-a-Custom-Module

When I compile from step (3), I get the following compilation error:
```
Linking target: FruityMesh.elf
/var/folders/qj/bys33jmj7p32jn6knf3bd9cw0000gn/T//ccBIx6jT.ltrans5.ltrans.o: In function `Node::Node(unsigned short)':
/Users/admin/nrf/projects/fruitymesh/./src/mesh/Node.cpp:107: undefined reference to `PingModule::PingModule(unsigned short, Node*, ConnectionManager*, char const*, unsigned short)'
collect2: error: ld returned 1 exit status
make: *** [all] Error 1
```

**Comment by microcosm** [comment]
btw I have included `PingModule.h` from `Node.cpp` (before you ask)

**Comment by microcosm** [comment]
OK, fixed. You have to manually add it as a source to Tim's makefile...
https://github.com/mwaylabs/fruitymesh/blob/master/makefile

**Comment by anujdutt9** [comment]
Hi. I am trying to compile the code but I am not able to do so. Can you please help me out.
Thanks : )
