### ISSUE TITLE
Node has old ID after enrollment

### ISSUE THREAD

**Issue by microcosm** [mwaylabs/fruitymesh#18]
Hi, I am attempting to enroll a node with an ID of 1. From the console I get the following output and the status LED goes green as expected. However after a hard reset the node ID is still 13314. Is there something extra I need to do to write-enable the persistent storage? Or can you suggest how to debug this?

```
mhTerm: action 13314 enroll nodeid 1 1
[EnrollmentModule.cpp@186 ENROLLMOD]: Enrollment (by nodeId) received nodeId:1, networkid:1
[Storage.cpp@118 STORAGE]: Writing len:34 to block:0
[Storage.cpp@71 STORAGE]: Event: 3, result:0, len:128
[Storage.cpp@71 STORAGE]: Event: 1, result:0, len:34
```

**Comment by mariusheil** [comment]
Hi,

do you have enabled persistent Storage for the node? Its available In the Config. If not, the values will not be written persistently.

Marius 

Sent from my Windows Phone.

----- Ursprüngliche Nachricht -----
Von: "Andrew McWilliams" <notifications@github.com>
Gesendet: ‎28.‎09.‎2015 21:08
An: "mwaylabs/fruitymesh" <fruitymesh@noreply.github.com>
Betreff: [fruitymesh] Node has old ID after enrollment (#18)

Hi, I am attempting to enroll a node with an ID of 1. From the console I get the following output and the status LED goes green as expected. However after a hard reset the node ID is still 13314. Is there something extra I need to do to write-enable the persistent storage? Or can you suggest how to debug this?
mhTerm: action 13314 enroll nodeid 1 1
[EnrollmentModule.cpp@186 ENROLLMOD]: Enrollment (by nodeId) received nodeId:1, networkid:1
[Storage.cpp@118 STORAGE]: Writing len:34 to block:0
[Storage.cpp@71 STORAGE]: Event: 3, result:0, len:128
[Storage.cpp@71 STORAGE]: Event: 1, result:0, len:34

**Comment by microcosm** [comment]
Do you mean these two?
`bool ignorePersistentNodeConfigurationOnBoot = false;`
and:
`bool ignorePersistentModuleConfigurationOnBoot = false;`

I have switched them both to `false`, and I get exactly the same results. LED goes green but the node ID is not changed after reset.

**Comment by mariusheil** [comment]
the other way round ;-) use true.

Sent from my Windows Phone.

----- Ursprüngliche Nachricht -----
Von: "Andrew McWilliams" <notifications@github.com>
Gesendet: ‎29.‎09.‎2015 05:34
An: "mwaylabs/fruitymesh" <fruitymesh@noreply.github.com>
Cc: "Marius Heil" <mariusheil@gmail.com>
Betreff: Re: [fruitymesh] Node has old ID after enrollment (#18)

Do you mean these two?
bool ignorePersistentNodeConfigurationOnBoot = false;
and:
bool ignorePersistentModuleConfigurationOnBoot = false;
I have switched them both to false, and I get exactly the same results. LED goes green but the node ID is not changed after reset.

**Comment by mariusheil** [comment]
sorry,wrong,... you were right of course....

Sent from my Windows Phone.

----- Ursprüngliche Nachricht -----
Von: "Andrew McWilliams" <notifications@github.com>
Gesendet: ‎29.‎09.‎2015 05:34
An: "mwaylabs/fruitymesh" <fruitymesh@noreply.github.com>
Cc: "Marius Heil" <mariusheil@gmail.com>
Betreff: Re: [fruitymesh] Node has old ID after enrollment (#18)

Do you mean these two?
bool ignorePersistentNodeConfigurationOnBoot = false;
and:
bool ignorePersistentModuleConfigurationOnBoot = false;
I have switched them both to false, and I get exactly the same results. LED goes green but the node ID is not changed after reset.

**Comment by microcosm** [comment]
Does this work for you? Are you able to enroll nodes with new IDs?

**Comment by mariusheil** [comment]
Yes, that works fine for me. Ill be able to test it in one week when i am back from holidays. i have some code that i have not yet pushed to github, but I dont think there was anything in there. you could listen for the outputs of the Storage class and look what's bring written.

Sent from my Windows Phone.

----- Ursprüngliche Nachricht -----
Von: "Andrew McWilliams" <notifications@github.com>
Gesendet: ‎29.‎09.‎2015 16:12
An: "mwaylabs/fruitymesh" <fruitymesh@noreply.github.com>
Cc: "Marius Heil" <mariusheil@gmail.com>
Betreff: Re: [fruitymesh] Node has old ID after enrollment (#18)

Does this work for you? Are you able to enroll nodes with new IDs?

**Comment by microcosm** [comment]
Thanks.

**Comment by mariusheil** [comment]
Hello,

how are things working for you? I'm back from  holidays and can now look into the problem. Did you manage to enroll nodes?
