### ISSUE TITLE
Support for new nrfconnect SDK

### ISSUE THREAD

**Issue by rench9** [mwaylabs/fruitymesh#185]
Hey,
Just curious to know if new **nrfconnect SDK** is compatible with fruitymesh and are you guys planning to integrate it.
Also if someone can suggest the level of effort we should look forward to, if we port the fruitymesh with new **nrfconnect SDK** in-house.

Thanks!

**Comment by mariusheil** [comment]
Hi,

FruityMesh is currently not compatible with the nrf connect SDK, we are still using the nRF SDK with the SoftDevice's. We will migrate at one point but currently do not have it on our roadmap as the SoftDevice supports all necessary features for our use-cases.
It is possible to port it and as a rough estimate I would assume it will take one developer between 2 - 6 weeks to do the porting. Might be more depending on the skillset. We have done porting to a cypress chipset in the past, which took us around 2 months but all the improvements in abstraction have gone into our codebase in the meantime which means it is easier now. Also, the support and documentation for cypress was really subpar when compared to the typical nordic documentation and support and we were running in a lot of unnecessary trouble.

Marius
