### ISSUE TITLE
LoRaWan module

### ISSUE THREAD

**Issue by bobmorane83** [mwaylabs/fruitymesh#197]
Hi,

First of all, thanks for the hard work done so far !

I've compiled the Fruitymesh stack on different platform and on the RAKWireless RAK4630 and seems to work ok.
I was wondering if a Fruitymesh LoRaWan module exist ? 
I've seen the work done by RAKWireless on the RAK4630 but unfortunatly for my project, based on Arduino environment.
I'am ready to port the Semtech stack (some project exist but quite old) but if BlueRange have done some work, I would be pleased to exchange on this subject.

Thanks,
BR,

**Comment by mariusheil** [comment]
Sorry, looks like this issue went under the radar. We have done some work with LoRaWan some time ago but have not followed up on this. So no, I do not know of any work in this direction, sorry.

I am closing this, but feel free to re-open it.

Marius

**Comment by bobmorane83** [comment]
No problem. 
I done it myself ;)
Best regards,
