### ISSUE TITLE
Does the Fruitymesh Binary include the softdevice?

### ISSUE THREAD

**Issue by Protoneer** [mwaylabs/fruitymesh#28]
I had a look at the deploy scripts and FruityMesh jlink file does net specify the memory location it writes to. Does the main that the Softdevice is included in the Binary and that it writes to memory location 0?

**Comment by mariusheil** [comment]
Hi,

you are right that there is no memory location given in the deploy script. This information is extracted from the .hex file and is generated during the link-process according to the linker scripts in the /linker folder. The application is placed right after the softdevice image (at 0x1c000 if I remember correctly).

Sent from my Windows Phone.

----- Ursprüngliche Nachricht -----
Von: "Bertus Kruger" <notifications@github.com>
Gesendet: ‎17.‎11.‎2015 04:02
An: "mwaylabs/fruitymesh" <fruitymesh@noreply.github.com>
Betreff: [fruitymesh] Does the Fruitymesh Binary include the softdevice? (#28)

I had a look at the deploy scripts and FruityMesh jlink file does net specify the memory location it writes to. Does the main that the Softdevice is included in the Binary and that it writes to memory location 0?

**Comment by Protoneer** [comment]
Thanks
