### ISSUE TITLE
Test Battery

### ISSUE THREAD

**Issue by junaediadi** [mwaylabs/fruitymesh#39]
Dear Marius,

I have question how to use test battery.cpp?
For example I want to do measurement with  those function (void TestBattery::advertiseAt100ms()).
Could you give me an example and how to implement that function?

Sincerely yours,

Junaedi Adi Prasetyo

**Comment by mariusheil** [comment]
Hello,

basically, this class should be used instead of the other initialization code in the main() function. It will then only execute some specific actions so that measurements can be done. By calling prepareTesting, some initialization code is executed which will then disable the default Node behaviour of discovery, connecting, etc,....

**Comment by junaediadi** [comment]
Dear Marius,
I have done with that.Thanks so much. Below is the result of advertising and scanning:
![scope_7](https://cloud.githubusercontent.com/assets/16444803/14279511/dafca69e-fb2d-11e5-82c7-dc575b88b8fc.jpg)

![scope_15](https://cloud.githubusercontent.com/assets/16444803/14279518/e4c877a2-fb2d-11e5-82f4-ca500e8f7fcc.jpg)

**Comment by mariusheil** [comment]
Perfect, looks good. Seems like you us the same scope that I used :-)

**Comment by junaediadi** [comment]
I use MSO X 3024 A.
I have question. I use advertising interval and scanning interval 100 ms, the rebuild new connection of two devices still take time around 2-3 seconds.is it right?

how to make the rebuild new connection at fruity mesh faster?

**Comment by mariusheil** [comment]
Hi,

it works the following. A node will scan for a longer interval to find a good set of other nodes that it could connect to. It will then decide which of these is the best connection partner. It cannot just connect to the first one available. Therefore it will take some time until it connects. This is controlled through the discovery and back off times.

**Comment by junaediadi** [comment]
I understand now. My idea now is to get the best setting for that,for example how long time to make new connection based on different times interval and scanning.
I will share the results of that to you and you can give the input to me.
