### ISSUE TITLE
UART communication bug

### ISSUE THREAD

**Issue by makerdiary** [mwaylabs/fruitymesh#42]
Hi guys,
I use UART for communication with a control application. nRF51822 will miss some characters when the host sends a string to it. Maybe it has bug in simple_uart. Have you ever meet this problem?
I am trying to use FIFO in uart.

Thanks.

**Comment by alanzheng800** [comment]
use fifo_uart will be OK ,i have try it .

**Comment by makerdiary** [comment]
Yes, fifo uart is OK.

**Comment by mariusheil** [comment]
Do you use hardware flow control? I do sometimes notice problems where a command is not recognized properly. It is probably better to use an interrupt driven UART implementation.

**Comment by alanzheng800** [comment]
i don`t use flow control .but i use a new fifo to buffer data ,then use old code to receive it one by one.and must use a counter to count time.if not do that ,it will not work good.

**Comment by mariusheil** [comment]
Is this bug still open, or closed? I am not sure?

**Comment by makerdiary** [comment]
FIFO should be used.
