### ISSUE TITLE
nRF5 SDK support

### ISSUE THREAD

**Issue by Informatic** [mwaylabs/fruitymesh#44]
Hello.
Are there any plans on migrating over to recent nRF5 SDK? It looks like it'd need some changes (mostly slight SDK name changes like GATTC vs GATT in some defines), but haven't looked into it deeply.

I don't feel like repeating work someone might have already done. @mariusheil? :)

**Comment by mariusheil** [comment]
Currently on it. I've got it running on SDK 11 currently. I've got tons of changes to the sourcecode that I want to publish. Only Problem is that I keep getting different tasks every few minutes and cannot focus on one thing. I really want to publish it this week.

**Comment by mariusheil** [comment]
it's up
