### ISSUE TITLE
get_device_info returns invalid deviceType for remote nodes

### ISSUE THREAD

**Issue by Informatic** [mwaylabs/fruitymesh#50]
```
{"nodeId":7124,"type":"device_info","module":3,"dBmRX":10,"dBmTX":10,"deviceType":0,"manufacturerId":65535,"networkId":3,"nodeVersion":30000,"chipId":"50:EB:57:20:33:22:11:00","serialNumber":"EDCBA","accessAddress":"55:44:33:22:11:00"}
{"nodeId":7123,"type":"device_info","module":3,"dBmRX":10,"dBmTX":10,"deviceType":43,"manufacturerId":65535,"networkId":3,"nodeVersion":30000,"chipId":"FE:E1:79:31:00:11:22:33","serialNumber":"ABCDE","accessAddress":"00:11:22:33:44:55"}
```

`action 0 status get_device_info` has been issued on 7124, `deviceType` for 7123 is 43, which is invalid. Neither of these devices were listed in testDevices array and persistent config has been set to be ignored.

(I'll look into it, just noting it down)

**Comment by mariusheil** [comment]
I haven't experienced this and can't reproduce the error, maybe the variable wasn't initialized properly. I changed some of this with the latest release, maybe this works for you.
