### ISSUE TITLE
Support for BLE Modules apart from Nordic Semiconductor ?

### ISSUE THREAD

**Issue by anujdutt9** [mwaylabs/fruitymesh#59]
Hi. I have tried the fruityMesh using the nrf51 dongle and it works really good. I was just thinking that is it possible to flash the same firmware to any other BLE module or board other than Nordic. ex. BLE Modules on board by STmicroelectronics or NXP ?
If it can be done, can you please guide me on how I can do that.
Thanks : )

**Comment by Informatic** [comment]
You'd have to pretty much reimplement 95% of the code here, as this is
really tightly based on Nordic BLE SoftDevice API.

**Comment by anujdutt9** [comment]
Well, are there any plans to implement this for other boards too in the future ?
