### ISSUE TITLE
The Algorithm in Detail question

### ISSUE THREAD

**Issue by xiamaiani** [mwaylabs/fruitymesh#68]
Hello, 

In The Algorithm in Detail part of the Wiki i read in the evaluation part that only broadcasting was implemented.
Is this the case only for the simulation or for the project as a whole?

Kind regards

**Comment by mariusheil** [comment]
Hi,

currently the Data is broadcasted over the Connections (not to be mistakened with Advertising Messages), but this isn t critical. It does not cost much more energy than an idle Connection. It will mostly limit the throughput of the mesh. It is possible to add some intelligent routing if needed without changing a lot of code.

----- Ursprüngliche Nachricht -----
Von: "xiamaiani" <notifications@github.com>
Gesendet: ‎04.‎11.‎2016 14:45
An: "mwaylabs/fruitymesh" <fruitymesh@noreply.github.com>
Betreff: [mwaylabs/fruitymesh] The Algorithm in Detail question (#68)

Hello,
In The Algorithm in Detail part of the Wiki i read in the evaluation part that only broadcasting was implemented.
Is this the case only for the simulation or for the project as a whole?
Kind regards

**Comment by xiamaiani** [comment]
Hello,

I was
