### ISSUE TITLE
Whitelist devices by address

### ISSUE THREAD

**Issue by lioninacoma** [mwaylabs/fruitymesh#78]
Hello,

I am writing my bachelor thesis about ble meshes and I am currently working with your connection based solution. I flashed the firmware on my Adafruit Bluefruit LE Friend and on my 3 Waveshare NRF51822 Eval Kits. The Bluefruit LE is connected to my Raspberry Pi Gateway. Data from the gateway software is transfered over UART to the ble stick, which is then forwareded over ble (encryption enabled) to the mesh devices. 

Now, I would like to authenticate every device that wants to connect to the mesh. To achieve that, the gateway broadcasts a list of 48 bit device addresses that are allowed. Every device stores these addresses in a whitelist, that is managed by my authentication module. When receving an advertisement message, a mesh device checks the peer address against its whitelist. Is the peer not whitelisted, the advPacket is removed from the joinMePacketBuffer and the messageType of the ad packet is set to -1, so no further processing is possible. Is the device whitelisted, the device connects to the mesh and updates its whitelist.

By looking at the Advertisement Controller, I noticed the advertisement params already have a whitelist. Is it possible to use this whitelist? Because, as I understand, a peer manager (device manager) has to maintain these whitelists, which is not implemented (?). If possible, can you alter this whitelist at runtime? Is there another way to block connection requests of devices by there address at deeper level?

Best regards,
Frederick Schubert

**Comment by mariusheil** [comment]
Hi,

I was on holidays for the last days, so I am respnding now. You are right,
that whitelists are not yet implemented nor are they used by my
implementation. The only thing you can do to block devices from making a
connection is to whitelist devices by using the whitelist that you
mentioned. This is the only thing that the BLE spec allows you. If you need
more fine granular control or an authentication on a higher level, you can
choose to use e.g. security (e.g. a certain encryption key that all your
devices know) are to do some authentication in a handshake after the
connection was done. However this will lead to devices that must first
connect and do the check after the connection was initialized.

Marius

2017-04-08 13:33 GMT+02:00 lioninacoma <notifications@github.com>:
