### ISSUE TITLE
Measure advertising packet rssi of surrounding nodes

### ISSUE THREAD

**Issue by mariusheil** [mwaylabs/fruitymesh#8]
The rssi of received advertising packets from surrounding nodes should be saved and reported with the connections packet so that a useful distance-graph can be built with this data.

**Comment by alanzheng800** [comment]
hi,mariusheil
i use cmd "action 0 status get_nearby" to one node ,but it return 
"{"nodeId":13360,"type":"nearby_nodes","module":30,"nodes":[]}"
i am sure it had connected to another node,why?
ps:i have two node ,they work good .

**Comment by mariusheil** [comment]
Nearby nodes doesn't return connected nodes. It does only return nodes that it recognized through advertising packets. (when receiving a JOIN_ME packet). You can instead type action 0 status get_connected to get all connected nodes.
