### ISSUE TITLE
Nordic SDK v13 support

### ISSUE THREAD

**Issue by onionhammer** [mwaylabs/fruitymesh#80]
I take it this is built to work with v11 of the SDK - are there any plans to support v12?

**Comment by mariusheil** [comment]
Yes, its planned, but timeline ist not clear yet as it hasn't been necessary so far. Sadly v13 is nrf52 only. If you want, you can try v12. Porting has been pretty easy in the past.

----- Ursprüngliche Nachricht -----
Von: "onionhammer" <notifications@github.com>
Gesendet: ‎12.‎06.‎2017 00:26
An: "mwaylabs/fruitymesh" <fruitymesh@noreply.github.com>
Cc: "Subscribed" <subscribed@noreply.github.com>
Betreff: [mwaylabs/fruitymesh] Nordic SDK v12 support (#80)

I take it this is built to work with v11 of the SDK - are there any plans to support v12?
