### ISSUE TITLE
Encryption for all mesh connections

### ISSUE THREAD

**Issue by mariusheil** [mwaylabs/fruitymesh#9]
It must be possible to encrypt all connections in the mesh, we should therefore introduce a mesh-wide encryption key. This is step 1. Afterwards, we should ensure that JOIN_ME packets are also at least authenticated so that no attacker can break up mesh connections and disturb the algorithm.

**Comment by mariusheil** [comment]
Step one is done, we have experimental encryption that works for mesh connections.

**Comment by anujdutt9** [comment]
How to use this encryption in sending messages and how to see that the message is encrypted ?
Thanks : )
