### ISSUE TITLE
Sensor data

### ISSUE THREAD

**Issue by lindeoo** [mwaylabs/fruitymesh#93]
I have working fruitymesh on nRF52 and I want to send data from the external temperature sensor through the mesh. How the I/O module could be used with a external continuous temp sensor ? As I understand the I/O is only usefull for high/low settings for GPIO. Thanks

**Comment by mariusheil** [comment]
Hi, the IO module won't help you. You have to implement a driver for the temperature sensor or use some available code to read the temperature from the sensor. You should probably include this in your own module or integrate it in the statusReporterModule.
