### ISSUE TITLE
how to use AppConnections ?

### ISSUE THREAD

**Issue by alanzheng800** [mwaylabs/fruitymesh#98]
Your mesh stack is very good! I want to use it in my product. but,how to use a phone connect to it .If you have a example,please contact me !

**Comment by mariusheil** [comment]
Hi,

sorry for the late comment. I am working to get a new version to Github, but there is not enough free time right now to clean it up and publish it. What are you planning to do?
You can inherit from the AppConnection and use the ResolverConnection to detect the connection type. Maybe if you have a look, you will get the idea and I can help you with some more specific question as I currently do not have an example that I could give you.

Marius

**Comment by OSPro** [comment]
Hi, i have same question. For example, how i send command to all nodes inside network from Mobile APP like Android?

**Comment by mariusheil** [comment]
Take a  look at the new MeshAccessConnections which is a general aproach on how to communicate with an app. We have an iOS implementation for that but there is now timeline on when this goes open source yet.
